# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-22 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_practice_app', '0007_auto_20180722_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
